---
title: "Actividad Quirófano"
subtitle: "Lectura y Unión de Registros"
execute: 
  echo: false
  include: false
  
---




```{r}

library(tidyverse)
library(purrr)
library(readxl)
library(janitor)
library(hms)

```




```{r}


read_qfnos <- function(path = NULL, servicio = NULL){
  
  df <- read_excel(path, skip=5) %>% 
    clean_names("snake") %>%
    mutate(servicio = servicio) %>%
    mutate(fecha = as.Date(fecha, "%d/%m/%Y"),
           mes = month(fecha),
           anio = year(fecha)
           ) %>%
    select(servicio, fecha, mes, anio, everything()) 
  
  assign(x = paste0(servicio, "_qfno"), df, envir = .GlobalEnv)
}


map_qfnos <- tibble(
path =  paste0("data/",c(
  "cto",              # 1
  # "tra_cadera",       # 2
  # "tra_rodilla",      # 3 
  # "tra_columna",      # 4
  # "tra_fracturas",    # 5
  "der_hums",         # 6
  "der_def"
  ),     # 4
  ".xls"),

servicio = c(
  "CTO",              # 1
  # "TRA_CADERA",       # 2
  # "TRA_RODILLA",      # 3
  # "TRA_COLUMNA",      # 4
  # "TRA_FRACTURAS",    # 5 
  "DER_HUMS",         # 6
  "DER_DEF"
  )      
)

pwalk(map_qfnos, read_qfnos)


```



```{r}


objetos <- ls()

# Selecccionamos los objetos cuyo nombre termina en "_cceee"
objetos <- objetos[grepl("_qfno$", objetos)]    

# Creamos una lista de los objetos seleccionados
lista_objetos <- lapply(objetos, get)

# Combinar los objetos en un solo data frame
ALL_qfnos <- do.call(rbind,lista_objetos)

write_excel_csv(x = ALL_qfnos, file = "ALL_qfnos.csv")


```

